#add Users to receive daily reports here
receipients: support@vas-consulting.com
#ADD ADMIN MSISDNs to receive sms for downtime here
admin_numbers: 260979411970, 260978980056
admin_emails: support@vas-consulting.com
subscriber_type: shortcode,prepaid,postpaid
enable_weekly: true
enable_monthly: true
enable_csv: true
enable_transaction_report: true




























































#DO NOT TOUCH THIS PORTION IF YOU ARE NOT A STAFF OF VAS-CONSULTING
#oracle server configuration
nodes_to_monitor: air,ema,broker,rim
adapter: mysql
oracle_user: bblite
oracle_password: Airtel2011
oracle_ip: 172.27.128.122
oracle_sid: bblitezm
sender: SL VAS REPORTS <reports@vas-consulting.com>
sender_password: passw0rd$
opco: Sierria Leone
air_ip: 10.26.202.87
air_port: 10010
air_username: bblite_ucip
air_password: ucip@bblite2
ema_ip: 10.26.204.71
ema_port: 3300
ema_user: bblite_ema
ema_password: em@bblite2
broker_ip: 127.0.0.1
broker_port: 8051
rim_url: celtelzm.provisioning.blackberry.com
rim_username: bbliteZM
rim_password: Airtelzm01
test_msisdn: 260973711193
test_imsi: 645017719123095 
mysql_user: root
mysql_password:
mysql_database: bblite
